In [42]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [43]:
path = "insurance_data.csv"

In [44]:
data = pd.read_csv(path)
data.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [23]:
# storing value which we are going to predict in y
y = data["bought_insurance"]
# droping the feature brought_insurance
X = data.drop(columns=["bought_insurance"])

In [24]:
#feature scaling
X["age"] = X["age"]/100

In [25]:
X

age  affordibility
0   0.22              1
1   0.25              0
2   0.47              1
3   0.52              0
4   0.46              1
5   0.56              1
6   0.55              0
7   0.60              0
8   0.62              1
9   0.61              1
10  0.18              1
11  0.28              1
12  0.27              0
13  0.29              0
14  0.49              1
15  0.55              1
16  0.25              0
17  0.58              1
18  0.19              0
19  0.18              1
20  0.21              1
21  0.26              0
22  0.40              1
23  0.45              1
24  0.50              1
25  0.54              1
26  0.23              1
27  0.46              1

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=25)

In [27]:
y_train.shape

(22,)

In [28]:
#!pip install scikit-learn

In [29]:
def sigmoid(x):
    return 1 / (1 +   np.exp(-x))

In [30]:
sigmoid(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [45]:
#w is initilize to one
W = np.ones((len(X.columns),1))
b = 1

In [46]:
np.transpose(W)

array([[1., 1.]])

In [47]:
#given x,w predict the value of y
def prediction(X, W, b):
    weighted_sum = np.dot(X,W)+b
    return sigmoid(weighted_sum)

In [48]:
prediction([.47,1],W,b)

array([0.92201176])

In [50]:
epsilon = 1e-15
# Binary cross entropy
def log_loss(y,y_):
    # handle log(0), log(1-1) these kind of cases
    y_ = [epsilon if ele == 0 else ele for ele in y_]
    y_ = [1-epsilon if ele == 1 else ele for ele in y_]
    #print(y_)
    y_ = np.array(y_)
    return -np.mean(y*np.log(y_)+(1-y)*np.log(1-y_))

In [51]:
y = np.array([1,2,3])
y_ = np.array([1,0,1])
log_loss(y,y_)

-0.0005330649534632433

In [54]:
def gradient_descent(X,y,epochs =5,rate = 0.5):
    # initialize w
    W = np.ones(len(X.columns))
    #print(W.shape)
    b = 0
    n = len(X)
    
    for i in range(epochs):
        y_predicted = prediction(X,W,b)
        #print(y_predicted)
        
        b_derivative = np.mean(y_predicted-y)
        w_derivative = (1/n)*np.dot(np.transpose(X),(y_predicted-y))
        #print(w_derivative)
        W = W -rate * w_derivative
        #print(W)
        b = b - rate * b_derivative
        loss = log_loss(y,y_predicted)
        
        
        #implement accuracy
        accuracy =1 
        if i%50==0:
            print(f'epoch : {i} , W : {W}, bais : {b:.4f}, loss : {loss:.4f}, accuracy : {accuracy:.4f}')
        
    return W,b

In [55]:
gradient_descent(X_train, y_train,epochs=1000)

epoch : 0 , W : [0.97490763 0.94834813], bais : -0.1134, loss : 0.7113, accuracy : 1.0000
epoch : 50 , W : [1.50331955 1.10838479], bais : -1.2319, loss : 0.5676, accuracy : 1.0000
epoch : 100 , W : [2.20071313 1.2941584 ], bais : -1.6607, loss : 0.5391, accuracy : 1.0000
epoch : 150 , W : [2.84957278 1.36968955], bais : -1.9861, loss : 0.5176, accuracy : 1.0000
epoch : 200 , W : [3.44301697 1.40422186], bais : -2.2571, loss : 0.5005, accuracy : 1.0000
epoch : 250 , W : [3.98245049 1.42391273], bais : -2.4944, loss : 0.4865, accuracy : 1.0000
epoch : 300 , W : [4.47217952 1.43878799], bais : -2.7074, loss : 0.4751, accuracy : 1.0000
epoch : 350 , W : [4.91724587 1.45256608], bais : -2.9012, loss : 0.4656, accuracy : 1.0000
epoch : 400 , W : [5.32256217 1.46648101], bais : -3.0788, loss : 0.4577, accuracy : 1.0000
epoch : 450 , W : [5.69260053 1.48081125], bais : -3.2422, loss : 0.4512, accuracy : 1.0000
epoch : 500 , W : [6.03131497 1.49549387], bais : -3.3931, loss : 0.4456, accuracy 

(array([8.27023952, 1.63322284]), -4.425953608965704)